# Generated by Django 5.1.6 on 2025-03-09 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanishi kerak', regex='^\\+998\\d{9}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Noma'lum", max_length=100)),
                ('weight', models.FloatField()),
                ('origin', models.CharField(default="Noma'lum", max_length=100)),
                ('destination', models.CharField(default="Noma'lum", max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Bortli', 'Bortli'), ('Tentli', 'Tentli'), ('Refrigatorli', 'Refrigatorli'), ('Samosval', 'Samosval'), ('Shalanda', 'Shalanda'), ('Konteyner', 'Konteyner'), ('Ploshadka', 'Ploshadka')], default='Bortli', max_length=20)),
                ('status', models.CharField(choices=[('Jarayonda', 'Jarayonda'), ('Yolda', 'Yolda'), ('Yetkazib berilgan', 'Yetkazib berilgan')], default='Jarayonda', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cargos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CargoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.cargo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('license_type', models.CharField(blank=True, max_length=50)),
                ('vehicle_capacity', models.FloatField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.driverprofile'),
        ),
    ]
